### ISSUE TITLE
Comments everywhere

### ISSUE THREAD

**Issue by tshoang** [eventB-Soton/XEventB#24]
Currently, comments are restricted to before the modelling elements (Multi-line) or after the modelling elements (single-line). This is quite restrictive and due to the translation of the comments into the Rodin elements. We should allow comments everywhere by ignoring them, however it means that the comments will no longer be kept in the underlying Rodin elements (but that is OK).

**Comment by tshoang** [comment]
We will have to disable the comment translation from Event-B to XText (make it transient).

**Comment by dd4g12** [comment]
Fixed for both context and machine and ready for next realease (0.08)
