### ISSUE TITLE
Errors in the generated Machine

### ISSUE THREAD

**Issue by leuschel** [eventB-Soton/XEventB#33]
I have tried to copy and paste a machine from Camille (non-X version).
I had to reformat slightly.
For some reason the begin was not accepted for the INITIALISATION (contrary what seems to be used in the Camille guide PDF).
I had to rename when to where.
After some tweaks I got the contents to pass through CamilleX.
HOwever, the generated .bum files contains several errors.

Here are the contents:
machine XTransfer0
variables b c
invariants
 @inv1: b∈ℕ // the bank account
 @inv2: c∈ℕ // the client account, no overdrafts
 @inv3: b+c = 10  // total sum of credits: 10
events
  event INITIALISATION
   then
    @ini1: b := 5
    @ini2: c ≔  5
  end
  event b2c where @g1 b>0 then
    @a1: b ≔ b−1
    @a2: c ≔ c+1
  end
  event c2b where @g1 c>0 then
    @a1: b ≔ b+1
    @a2: c ≔ c−1
  end
end

The Rodin errors are:
Description	Resource	Path	Location	Type
Lexical error. Character : has been ignored	XTransfer0.bum	/CamilleXTests	Unknown	Rodin Problem Marker
Syntax error: Operator: ≔ should appear at the beginning of a sub-formula	XTransfer0.bum	/CamilleXTests	Unknown	Rodin Problem Marker
Syntax error: Operator: ≔ should appear at the beginning of a sub-formula	XTransfer0.bum	/CamilleXTests	Unknown	Rodin Problem Marker
Syntax error: Operator: ≔ should appear at the beginning of a sub-formula	XTransfer0.bum	/CamilleXTests	Unknown	Rodin Problem Marker
Syntax error: Operator: ≔ should appear at the beginning of a sub-formula	XTransfer0.bum	/CamilleXTests	Unknown	Rodin Problem Marker
Syntax error: Unknown operator:  (expected to find an assignment operator)	XTransfer0.bum	/CamilleXTests	Unknown	Rodin Problem Marker

After adding a : after the two labels @g1 some of the errors disappeared, but there is still a lexical error for ini1; somehow the := is not converted to its Unicode equivalent.

**Comment by tshoang** [comment]
Dear Michael,
We adopt the syntax from Camille for event, i.e., any ... where ... then ... end. So there are no "begin" keyword any more. The advantage of that is one can comment out part of the event without changing keyword. (I have to check the documentation again as it was rewritten and it might have some "begin" left-over).

Another syntax different with Camille is that we required ":" after the guard. Also := will not be automatically translated, i.e., you need to convert that into Unicode symbol using content assist. During typing, content assist will be invoked automatically after special characters such as ":", however, it will not do it if a chunk of code is pasted. We did attempt to run the Rodin keyboard converter automatically, but we seem to disable it now. (@dd4g12: Do you remember why we did not do this any more?).

**Comment by dd4g12** [comment]
Hi Son and Michael,

I just checked, it seems the code calling the Rodin keyboard was commented out by mistake when we removed the string quotes for predicates.

Kind Regards,
Dana

**Comment by tshoang** [comment]
@dd4g12 I think it was the case that the underlying EMF is translated but the CamilleX editor was not refreshed isn't it?

**Comment by dd4g12** [comment]
@tshoang I just fixed it I will send a pull request. It was done with the string conversion when we removed the double quotes of predicates, I was calling the Rodin keyboard at the same time, but when we removed the quotes this was removed as well.

**Comment by tshoang** [comment]
@leuschel The (might be easier) way to get the CamilleX file is to convert the Rodin Event-B files using context menu. However, comments will not be translated. If there are lots of comments, copy from Camille text editor to CamilleX and adapt the slight differences syntax will be less effort.

**Comment by dd4g12** [comment]
@tshoang Oh I just remembered,  that's true as well. CamilleX will not convert the symbols but they will only be converted in event-b.

**Comment by tshoang** [comment]
The conversion is now done in the XMachine generator.
