### ISSUE TITLE
Saving does not seem to update Rodin representation

### ISSUE THREAD

**Issue by leuschel** [eventB-Soton/XEventB#37]
I have intentionally created an error in a machine, using  a variable that does not exist (Ss in the last line of the context shown below).
Saving the file in CamilleX did not create an error marker nor error message, despite Build and Prove automatically being enabled.
I often have a similar issue with Camille at the moment; the Event-B context editor does not have this issue.

![screenshot 2018-11-19 at 12 41 54](https://user-images.githubusercontent.com/1742246/48705292-11a1ca80-ebf9-11e8-928b-75c821a16c4f.png)

**Comment by tshoang** [comment]
Dear @leuschel,
 It seems to me that the issue related to the link between EMF layer and RodinDB (similar on the other issue). We will take a closer look at it when @cfsnook is back.
 Best regards,
Son

**Comment by tshoang** [comment]
We close this issue for now as it seems to be fixed by the current version of CamilleX. Please reopen this issue if the problem reappears (we might need more information, e.g., the project archive, to debug this).
