### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [eventB-Soton/XEventB#38]
Hello XEventB team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477).

If you are interested that the XEventB project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>

```
We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by tshoang** [comment]
<tr>
	<td><a href="project_link">Event-B CamilleX</a></td>
	<td>This feature provides XText-based editors for Event-B components within the Rodin Platform (http://wiki.event-b.org/). It also extends the Event-B method for compositional modelling.</td>
	<td>Eclipse Public License v1.0</td>
	<td>System Modelling</td>
	<td>Michael Butler, Dana Dghaym, Thai Son Hoang, Asieh Salehi-Fathabadi, Colin Snook</td>
</tr>

**Comment by miklossy** [comment]
Thank you @tshoang !

**Comment by tshoang** [comment]
@miklossy : Please edit the category accordingly, if you that it fits with other existing categories that you have. Thank you very much.

**Comment by miklossy** [comment]
The `Event-B CamilleX` project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).
