### ISSUE TITLE
generate (all) Rodin components

### ISSUE THREAD

**Issue by cfsnook** [eventB-Soton/XEventB#58]
It would be useful to have a menu option to re-generate selected (or all) machines and contexts in a project.

There are a few use cases where this is needed - e.g. if a project is shared in a repo, we may not track the bum and buc files because they have a lot of spurious changes.

At the moment i have to open each CamilleX file  and make a change and save it and then revert the change and save it again.

**Comment by tshoang** [comment]
I think ultimately, this is related to XText builder that need to be improved for CamilleX. Ideally, a clean/build should do the job, but it is not done at the moment.

**Comment by tshoang** [comment]
This is a duplication of Issue #63
